### ISSUE TITLE
Can we include Single Jar packaging for easy & simple solution

### ISSUE THREAD

**Issue by sarkershantonu** [RaiMan/SikuliX2#11]
In place of using maven jar plugins, if we use maven assembly plugins , we can actually package everything in single jar . So that when a non tech QA run the jar, they can run easily, no need setup process. (i did in in office already from source) 
this will allow not dependent on setup wizard which goes to Dropbox (which is not allowed in corporate environments)

**Comment by RaiMan** [comment]
The actual setups (1.1.0 and 1.1.1) do not go to Dropbox any more.
Everything is downloaded from MavenCentral (or OSSRH for snapshot/nightly versions).

As a fallback you always have the option for offline setup.

You have to live with this situation in version 1.1.x.
Version 2 might bring additional options.

**Comment by sarkershantonu** [comment]
we faced this issue (going to drop box) from this installer 
https://launchpad.net/sikuli/sikulix/1.1.0
As in our corporate network, dropbox is block, we had to build from source.

**Comment by RaiMan** [comment]
please send me the setup log file to sikulix--at--outlook--dot--com

setup 1.1.0 should not access any Dropbox content.

**Comment by sarkershantonu** [comment]
i send email(from office mail)  including log and thread dump of setup jar which used to be halted due to no communication from server.

**Comment by RaiMan** [comment]
got it.
the "Dropbox" in the popup text is simply a bug.
Better information is in the log, where you can see, that all downloads are blocked somehow (bot nothing is tried to be downloaded from Dropbox)

Manually downloading according to the docs is the correct solution.

**Comment by sarkershantonu** [comment]
yes, due to this, I make the standalone jar. From company , we are planning this to use for all manual testing activity as well as with selenium.

Thanks
