### ISSUE TITLE
Sikulix not working

### ISSUE THREAD

**Issue by p0l3y** [RaiMan/SikuliX2#19]
After a lot of work, I was finally able to set up Sikuli on my computer, I just had to run the Sikuli-IDE.sh script to run the ide. However nothing happens when I run this script. Please help.

**Comment by Tokeiito** [comment]
Very vague comment. Too little information to help you. Please provide following information:
 * Operating system name/version
 * Java version
 * Any errors from Sikulix setup log
 * SikuliX version
 * Any error output you are getting when SikuliX fails.

**Comment by p0l3y** [comment]
Sorry for the vagueness.
* Ubuntu 16.04
* Java version: "1.8.0_111"
* no errors
* Sikulix 1.1.0
* no errors
* I installed Sikulix (after many failed attempts in various other ways) by downloading the .jar file from this link: https://launchpad.net/sikuli/sikulix/1.1.0/+download/sikulixsetup-1.1.0.jar

**Comment by lucrib** [comment]
Hi @p0l3y 
Please, take a look at [the linux pre-requisites ](http://sikulix.com/specials/files/linux-setup-prerequisites.html) to see if you find any help and then follow the instructions on [quickstart guide](http://sikulix.com/quickstart/).
If you still have no success come back and comment here.

**Comment by RaiMan** [comment]
switch to version 1.1.1
http://sikulix.com
... and follow the advice @lucrib above
