### ISSUE TITLE
Release or fix the release date

### ISSUE THREAD

**Issue by aolko** [RaiMan/SikuliX2#20]
So, yet another delay, huh? That was expected.

**Comment by RaiMan** [comment]
Happy new year also to you.

**Comment by Forgen** [comment]
Happy 😄 New Year RaiMan 🍾!!  Thanks for all your hard work,  Sikuli is great. I look forward to trying to contribute to the project this year.

**Comment by RaiMan** [comment]
@Forgen 
all the best and always welcome.
