### ISSUE TITLE
Use for VM app testing

### ISSUE THREAD

**Issue by iltempe** [RaiMan/SikuliX2#23]
Nice project!
I have a Win Pc and a Linux VirtualBox Machine with an app (linux) that I want to test from Windows. Is possible to use this tool? can you give me some indication about how can i do this? thanks!

**Comment by RaiMan** [comment]
start here:
http://sikulix.com

and use the nightly 1.1.1 version.

The VM Linux hopefully is an Ubuntu, which makes setup much easier. 
... and carefully read and follow the steps mentioned in "Getting started"
