### ISSUE TITLE
Need help in establishing VNC with SIkuliX or SikuliX2?

### ISSUE THREAD

**Issue by skmvali** [RaiMan/SikuliX2#24]
Hi RaiMan,

Thanks for your blog. It's really nice.

I need to connect to linux machine through Real VNC and run my sikuli scripts with Java API. Please help me to get APi location. Checked this SikuliX Java API docs http://nightly.sikuli.de/docs/index.html . But i dont see any classes related to VNC. If SikuliX still needs implimentation then help atleast in Sikuli old version. Thanks in advance.

Thanks

**Comment by RaiMan** [comment]
only available in version 1.1.1 (version 2 not yet useable)

look 
http://sikulix-2014.readthedocs.io/en/latest/screen.html#connecting-to-a-vnc-server-vncscreen

**Comment by skmvali** [comment]
Thank you for quick reply...
