### ISSUE TITLE
Unable to use urllib2.urlopen

### ISSUE THREAD

**Issue by GoTo-Romania** [RaiMan/SikuliX2#25]
**System:**
SikulixIDE 1.1.1
Jython 2.7.0 (default:9987c746f838, Apr 29 2015, 02:25:11)
[Java HotSpot(TM) 64-Bit Server VM (Oracle Corporation)] on java1.8.0_121
Windows 7 64-Bit

**I have this code in SikulixIDE:**

```

  import urllib2
  response = urllib2.urlopen('http://www.drona.ro/')
  html = response.read()
  print(html)

```
and I get the error that is at the bottom of this post.

**I also ran the code like bellow, and it worked:**
```

c:\>java -cp c:\Sikulix\sikulix.jar org.python.util.jython
Jython 2.7.0 (default:9987c746f838, Apr 29 2015, 02:25:11)
[Java HotSpot(TM) 64-Bit Server VM (Oracle Corporation)] on java1.8.0_121
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib2
>>> response = urllib2.urlopen('http://www.drona.ro/')
>>> html = response.read()
>>> print(html)
<!DOCTYPE HTML .......

```

**Error I get:**

```
Apr 17, 2017 4:17:11 PM org.python.netty.channel.AbstractChannel$AbstractUnsafe register
WARNING: Force-closing a channel whose registration task was not accepted by an event loop: [id: 0xa0c91719]
java.util.concurrent.RejectedExecutionException: event executor terminated
at org.python.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:745)
at org.python.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:322)
at org.python.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:728)
at org.python.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:420)
at org.python.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:60)
at org.python.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:48)
at org.python.netty.channel.MultithreadEventLoopGroup.register(MultithreadEventLoopGroup.java:64)
at org.python.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:317)
at org.python.netty.bootstrap.AbstractBootstrap.doBind(AbstractBootstrap.java:273)
at org.python.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:269)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
.....

[error] script [ sikuli ] stopped with error in line 3
[error] urllib2.URLError ( <urlopen error [Errno -1] Unmapped exception: java.util.concurrent.RejectedExecutionException: event executor terminated> )
[error] --- Traceback --- error source first line: module ( function ) statement 1214: urllib2 ( http_open ) File "C:\Sikulix\sikulix.jar\Lib\urllib2.py", line 1184, in do_open
421: urllib2 ( _open ) File "C:\Sikulix\sikulix.jar\Lib\urllib2.py", line 382, in _call_chain
127: urllib2 ( urlopen ) File "C:\Sikulix\sikulix.jar\Lib\urllib2.py", line 404, in open
[error] --- Traceback --- end --------------
```

**Comment by GoTo-Romania** [comment]
Nevermind! It works ok if you use ```runsikulix.cmd``` to start the IDE.

**Comment by GoTo-Romania** [comment]
It seems that it's working ok the first time you start the IDE but it gives this error the following times. It seems that some event is already registered and you can not register again the second time...

**Comment by RaiMan** [comment]
Your observation is correct:
In the IDE the same interpreter instance is used with each new run.
From commandline this is naturally not the fact.

I am not an expert with urllib2: is there any chance to reset it to a "closed" state at script end?

**Comment by GoTo-Romania** [comment]
It doesn't seem to be.

If you search for "urlib2 close" you will see that a lot of people have a similar problem. There was even a bug in Python [http://bugs.python.org/issue1208304](url) which would leave objects in memory after calling urllib2.urlopen().

I guess it's the same in Jython.

I tried some things, but none work: 
`response.fp._sock.recv = None
    response.close()`

**Comment by RaiMan** [comment]
A workaround:
- edit the script in the IDE 
- run it in parallel from commandline (be sure to have it saved after changes)

Since this is not a typical SikuliX issue, I will close it here, since there seems not to be any simple solution.

Another option is to try with the older module urllib or use respective Java libraries, which is easily possible in Jython.

If it is only your intention, to get the html source of some page, this is available:
import org.sikuli.basics.FileManager as FM
html = FM.downloadURLtoString("http://www.drona.ro")
print "html:", len(html)
uprint( html)

**Comment by GoTo-Romania** [comment]
Thanks RaiMan!
urlib gives the same error as urlib2 but org.sikuli.basics.FileManager is working! I didn't know it was available. 

Thanks again and have a nice day!

**Comment by RaiMan** [comment]
> I didn't know it was available.

You could not know that, since it is a "private" feature for internal use.

Glad I could help.
