### ISSUE TITLE
how to use redis in sikulixIDE 1.1.2 script 

### ISSUE THREAD

**Issue by sherry0429** [RaiMan/SikuliX2#29]
thanks your great work, this tool is excellent
i have see the FAQ : https://answers.launchpad.net/sikuli/+faqs
and i see here https://answers.launchpad.net/sikuli/+faq/2208

i have a script and i want to read data from redis,

i just download redis.tar.gz and unzip it, and copy it to ../sikulix../lib/redis

when i run script, import redis have no problem, but when i use it like:

import redis
r = redis.StrictRedis("localhost", 6379, 0)
and it raise exceptions,

can you tell me how to use third party python package in sikulixIDE scripts ? thanks

**Comment by RaiMan** [comment]
see:
http://sikulix-2014.readthedocs.io/en/latest/scenarios.html#using-python

be sure your redis module can be used with Jython.

**Comment by sherry0429** [comment]
thanks, i will check it
