### ISSUE TITLE
Automatic resize option for images in environments with other resolutions

### ISSUE THREAD

**Issue by sachinkademane** [RaiMan/SikuliX2#30]
Hi team,

i am using -> java version "9.0.1" and maven -> Apache Maven 3.5.4
i was trying to build this project by setting proxy and all pre requisites needed but while doing `mvn compile` following error was coming up
... removed ...
[INFO] Compiling 112 source files to C:\SikuliX2-master\target\classes
So how can i resolve this isuue?

**Comment by RaiMan** [comment]
as mentioned in the readme:

> Version 2.0.0 under developement (pre-alpha!) 
> (not useable yet, massive redesign planned until Oct. 2018)

Currently busy with some back ports to version 1.1.4 
(https://github.com/RaiMan/SikuliX1/tree/develop)

So what are you interested in?

**Comment by sachinkademane** [comment]
Hi Raiman, thanks for the reply
we are currently looking for the scaling issue for different resolutions in sikuli which we are expecting to be resolved in 2.0 version or is that the simple code fix which we can do?

**Comment by RaiMan** [comment]
A resize() option is available in latest 1.1.3 now.

see: http://sikulix-2014.readthedocs.io/en/latest/pattern.html#Pattern

**Comment by dmsurti** [comment]
@sachinkademane SikluliX-1.1.3 snapshot can be downloaded from: https://raiman.github.io/SikuliX1/nightly.html

Scroll down and see section starting with `For setup the only file you need to download is sikulixsetup-1.1.3-#timestamp#.jar: ` to download the  1.1.3 setup file.

**Comment by RaiMan** [comment]
SikuliX2 for now compiles again:
- removed API version 1.1.x
- switched off all tests

**Comment by RaiMan** [comment]
BTW: current implementation of version 2 does not have the resize option anyways ;-)
