### ISSUE TITLE
Judge whether image exist in other image questsion (program logical questions)

### ISSUE THREAD

**Issue by sherry0429** [RaiMan/SikuliX2#31]
hey RaiMan, this not a project issue, just my personal questions, would you give me some advice ? thanks.

I work on a auto test project now, and i need solve a problem like this:
1. image A and B
2.image A include B, B is part of A
3.i need make logical like :
`
if B in A:
    click()
else:
    time.sleep()
`
i have find some doc and use opencv matchTemplate methods, and now i can make program know where image B axis in image A.

but matchTemplate method return a Axis even if B not in A. How to solve this?

i see sikulix can find image in window and click them, judge if it exists and do operations.  would you tell me how sikulix finish this ? very thanks !

very simple questions:

how to make logical that : 
`
when image A in B, 
     do something, 
else 
     do something
`

**Comment by RaiMan** [comment]
SikuliX uses OpenCV matchTemplate internally, so no need to do your own implementation.

Are you really talking about images in images or images in regions on the screen?

Your problem, I guess is about similarity score.
With the latest version 1.1.4 another option might be transparency (ignore part of an image on search).

Could you send me image samples to my mail address (see https://github.com/RaiMan)

**Comment by RaiMan** [comment]
Greetings to your cat: have you checked, wether she/he can solve your problem ;-)
I have 2 cats and am familiar with this behaviour (including laying down over the whole keyboard).

- in what language do you script/program?
- why don't you use SikuliX - it has all you need?
- So I can not cut up and calculate similarity score??? so how do you get the small image?

The OpenCV example for matchTemplate is well documented and shows how to solve your problem "position of small in big image" .
The minMax gives access to the score value at a position, where matchTemplate found a match. If this score is smaller than 0.7 then it is most probably a false positiv, smaller than 0.9 it might be a false positiv and if greater than 0.9 it is most probably a found.

**Comment by sherry0429** [comment]
I ask my cat, she just turn around and left me an ass  :-)

- i use python
- sikulix see image on PC screen, but i am working for is make a web service to control my iOS decide like iPad & iPhone use auto test framework, So when i am not in my house, i can control them auto do some work like play games. device image is always change and hard to capture right images, 
- I get image step like this:
    - screenshot
    - get sub image in screenshot which i want to click, like buttons, icons, rewards etc.
    - run the program is will auto check current screenshot and check whether sub image in it, so program could know which status it is, and do different logical.

minMax is what i need ! 
`cv2.minMaxLoc(src[, mask]) → minVal, maxVal, minLoc, maxLoc`
so minVal & maxVal is minMax score ?

by the way, before know this way, i have make my framework become a recorder to memory my click step and position, and force add sleep between two click commands... it like a fool to click and click.. but also solve a part of my problem..

**Comment by RaiMan** [comment]
Cats showing her back either want to punish you by ignoring or want to hide, that they are ashamed about something (not able to help you in this case) ;-)

Yes, depending on the variant of matchTemplate it is either the combination of minVal/minLoc or maxVal/maxLoc (in case SikuliX: Imgproc.TM_CCORR_NORMED max, Imgproc.TM_SQDIFF_NORMED min).

as mentioned above:
The maxVal gives the score value at a position, where matchTemplate found a match. If this score is smaller than 0.7 then it is most probably a false positiv, smaller than 0.9 it might be a false positiv and if greater than 0.9 it is most probably a found.

All the best (greetings to your cat ;-)

BTW: any chance to look into your solution? No problem if not of course.

**Comment by sherry0429** [comment]
no problem, i do this work for my own, but it a little hard to explain,

all i want is to make play game more easier, i very like play summoners war but it waste a lot of time to do same things, i want to play it and not influence my life.

i am not upload my code to github because if this opened summoners war's developer may be ban it.

solution is like :
- cloud server , Mac, iOS device
- web application created by django & tornado & flask etc.
- iOS UITestFramework, like facebook webdriveragent

use jquery make a simple web page, and use python make some restful interface,

so use HTTP request to make server call webdriveragent client (called facebook-wda) API, so the device can be clicked.

the most hard question is:
- make webpage include some buttons like 'screenshot' and when you click screenshot show in browser, (x,y) will be transform to (x, y) on device screen. 

My solution include two webapplication,
- ClickRecorder to show current screenshot and record click commands as list, when do commands in list, it will record click order so when finish it can output a scripts with these commands.
- Responder to receive any http request from my device with verify sign code and do script above output

**Comment by RaiMan** [comment]
To avoid any risk, I removed the game name from your answer, which I appreciate very much.

I understand:
A website allows you to drive your iOS device by using facebook webdriveragent on the web server.

This is enough information for me currently.

Since SikuliX already has an experimental feature to access Android devices, I always watch out for a similar solution for iOS.
So I will now have a look at the facebook webdriveragent.

I will close this thread for now.

I am interested to stay in contact privately. If you agree, then send me a mail contact to use for that to sikulix---at---outlook---dot---com.

Anyways all the best.
